### PR TITLE
Remove talent buddy

### PR DESCRIPTION
**Pull request by stevepm**
The app shut down, unfortunately :(

### CODE REVIEW

**Comment by andreis** [comment]
Fuck! I knew some of these guys, really fantastic talent. Thanks for letting me know.

http://www.talentbuddy.co/blog/

**Comment by gameguy43** [comment]
Yeh, they had a really solid product!

**Comment by andreis** [comment]
Sorry but your PR will have to wait a bit. I'm very grateful for your help, but I plan to revamp/solve all issues in a bit, so it wouldn't make much sense to do this one small change now.

Thank you :+1: :star:

**Comment by ekosynth** [comment]
Why didn't they just leave it up? Why take it down?

**Comment by andreis** [comment]
Fixed https://github.com/andreis/interview/commit/8db9c60695ddfb6d5a54afe424a74ed2f7339699

**Pull request closed without merging**
