### PR TITLE
updates to Pramp info

### PR DESCRIPTION
**Pull request by matanzg**
Thanks for maintaining this great resource!

### CODE REVIEW

**Comment by andreis** [comment]
> Matan Goldschmiedt
> Co Founder & CTO at Pramp

Hi Matan

I appreciate the nice words and the contribution, and while I like Pramp (haven't used it enough to say more than that), I will not accept PRs with an agenda.

Thanks,
Andrei

**Comment by matanzg** [comment]
Hi Andrei,

Understood - can I update the PR to maintain the order, yet still include
the article? We believe it's a great read for interview preparation, check
it out!

**Comment by andreis** [comment]
Already pushed it and mentioned you, it's a great article!

**Comment by matanzg** [comment]
That's great, thanks!

**Pull request closed without merging**
